gap_finder:
  ros__parameters:
    scan_topic: /scan
    marker_topic: /gap_finder/triangle_markers
    half_fov_deg: 30.0
    # keep visual node's half_fov_deg in sync manually
    max_considered_range: 2.0
    cluster_eps: 0.12
    cluster_min_points: 10
    termionate_left_right_scan_data_median_distnace: 0.18
    approach_cmd_topic: /cmd_vel
    approach_forward_speed: 0.24
    approach_turn_speed: 0.35
    approach_turn_deadband: 0.02
    left_right_cluster_distance_margin_for_steering: 0.1
    corridor_enable_topic: /corridor/enable

corridor_controller:
  ros__parameters:
    scan_topic: /scan
    cmd_vel_topic: /cmd_vel
    half_front_degree_range: 30.0
    free_considered_range: 1.0
    obstacle_detect_distance: 0.33
    default_speed: 0.24  
    turning_speed: 3.0
    front_LR_steering_deadband: 0.05
    F_FL_FR_similar_threshold: 0.05
    steering_smoothing_gain: 0.1 # lesser, more smoothing
    last_LR_mean_steering_deadband: 0.05

tunnel_following:
  ros__parameters:
    scan_topic: /scan
    cmd_vel_topic: /cmd_vel
    half_fov_deg: 40.0
    max_considered_range: 1.0
    linear_speed: 0.12
    angular_speed: 0.45

corridor_enable_publisher:
  ros__parameters:
    enable_topic: /corridor/enable
    publish_period_sec: 0.5
