dbscan_finder:
  ros__parameters:
    scan_topic: /scan
    marker_topic: /dbscan_markers
    left_waypoint_topic: /dbscan/left_waypoint
    right_waypoint_topic: /dbscan/right_waypoint
    median_waypoint_topic: /dbscan/median_waypoint
    half_fov_deg: 40.0
    max_considered_range: 1.0
    cluster_eps: 0.12
    cluster_min_points: 10
    cluster_distance_threshold: 0.75
    steering_cmd_topic: /cmd_vel
    steering_linear_speed: 0.12
    steering_angular_gain: 2.0
    steering_max_angular_speed: 1.5
    close_cluster_distance: 0.35
    close_speed_ratio: 0.4

gap_finder:
  ros__parameters:
    scan_topic: /scan
    marker_topic: /gap_finder/triangle_markers
    half_fov_deg: 40.0
    # keep visual node's half_fov_deg in sync manually
    max_considered_range: 1.0
    cluster_eps: 0.12
    cluster_min_points: 10
    cluster_distance_threshold: 0.75
    approach_enable_margin: 0.05
    approach_cmd_topic: /cmd_vel
    approach_forward_speed: 0.18
    approach_turn_speed: 0.7
    approach_turn_deadband: 0.1
    corridor_enable_topic: /corridor/enable

corridor_enable_publisher:
  ros__parameters:
    enable_topic: /corridor/enable
    publish_period_sec: 0.5

corridor_controller:
  ros__parameters:
    scan_topic: /scan
    cmd_vel_topic: /cmd_vel
    half_front_degree_range: 30.0
    free_considered_range: 1.0
    obstacle_detect_distance: 0.33
    default_speed: 0.06  
    turning_speed: 3.0
    front_LR_steering_deadband: 0.05
    F_FL_FR_similar_threshold: 0.05
    steering_smoothing_gain: 0.1 # lesser, more smoothing
    last_LR_mean_steering_deadband: 0.05
    
tunnel_following:
  ros__parameters:
    scan_topic: /scan
    cmd_vel_topic: /cmd_vel
    half_fov_deg: 40.0
    max_considered_range: 1.0
    linear_speed: 0.12
    angular_speed: 0.45